algoritmo "semnome"
// Função :
// Autor :
// Data : 14/04/2022
// Seção de Declarações 
var
   contador, valor, valo: inteiro
   
inicio
      contador <- 0
      escreva ("Até quanto devo contar? ")
      leia (valor)
      escreva ("De quanto em quanto devo contar? ")
      leia (valo)
      Enquanto (contador <= valor) faca
      Escreval  (contador)
      contador <- contador + valo
      FimEnquanto

// Seção de Comandos 
fimalgoritmo
