algoritmo "semnome"
// Função :
// Autor :
// Data : 08/04/2022
// Seção de Declarações 
var
   draco, reais, dolar: real
inicio
      Escreval ("Quantos dracos você tem? ")
      Leia (draco)
      reais <- draco*3.8247
      dolar <- draco*0.8052
      Escreval ("Você tem atualmente ", reais, " reais.")
      Escreva ("Você pode ter ",dolar, " dolares.")
// Seção de Comandos 
fimalgoritmo
