algoritmo "semnome"
// Função :
// Autor :
// Data : 08/04/2022
// Seção de Declarações 
var
   num1: inteiro
inicio
      Escreval ("Digite o número e eu te direi se ele é par ou ímpar! ")
      Leia (num1)
      Se (num1 % 2 = 0) entao
         Escreva ("O número digitado é par! ")
      senao
           Escreva ("O número digitado é ímpar!")
      Fimse
// Seção de Comandos 
fimalgoritmo
